[M775] Fix dashboard org filtering bug
data-mermaid/mermaid-dash pull request #320
Opened 2024-05-10 17:22 UTC by tienhoah

- Refactor query strings to work correctly with special characters (such as '&' for organization 'Fauna and Flora International').
- Increase the bounding box range when map is initially loaded and zoom to sites/clusters.

2024-05-10 18:52 UTC, tienhoah commented
![](https://github.trello.services/images/mini-trello-icon.png) [dashboard org filtering bug?](https://trello.com/c/Sdljc9A3/775-dashboard-org-filtering-bug)

2024-05-13 14:19 UTC, saanobhaai requested changes
I think it looks good, though I'm not entirely clear how it fixes the bugs. Just one question before we merge to dev and try it out.

2024-05-13 14:19 UTC, saanobhaai commented on src/components/LeafletMap.js
> +      const markerBounds = markersCluster.getBounds()
Do you want to keep the `.pad(0.1)`?

2024-05-13 16:12 UTC, saanobhaai commented on src/components/LeafletMap.js
> +      const markerBounds = markersCluster.getBounds()
OK that makes sense

2024-05-13 16:12 UTC, merged